name: Test Coveralls

on: ['push', 'pull_request']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '16'

      - name: yarn install, yarn test:coverage
        run: |
          yarn
          yarn test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
